const soundBoard = {
    "50": "../audio_files/fifty.wav",
    "come": "../audio_files/comecomecomecome.wav",
    "coming": "../audio_files/comecomecomecome.wav",
    "money": "../audio_files/money.mp3",
    "whopper": "../audio_files/whopper.mp3",
    "annoying": "../audio_files/FluteRun.mp3",
    "loud": "../audio_files/loud.mp3",
    "hello there": "../audio_files/hello_there.mp3",
    "sorry": "../audio_files/sorry.mp3",
    "obamacare": "../audio_files/obamacare.mp3",
    "lag": "../audio_files/lag.mp3",
    "lost": "../audio_files/lost.mp3",
    "newt": "../audio_files/newt.mp3",
    "neutronium": "../audio_files/newt.mp3",
    "movie": "../audio_files/movie.mp3",
    "dead": "../audio_files/dead.mp3",
    "dying": "../audio_files/dead.mp3",
    "died": "../audio_files/dead.mp3",
    "die": "../audio_files/dead.mp3",
    "death": "../audio_files/dead.mp3",
    "killed": "../audio_files/dead.mp3",
    "kill": "../audio_files/dead.mp3",
    "clear comms": "../audio_files/clearcomms.mp3",
    "plastic": "../audio_files/biden.mp3",
    "extract": "../audio_files/tarkov.mp3",
    "afk": "../audio_files/afk.mp3",
    "goodbye": "../audio_files/goodbye.mp3",
    "goodnight": "../audio_files/goodbye.mp3",
    "good night": "../audio_files/goodbye.mp3",
    "or is it": "../audio_files/or_is_it.mp3",
    "leather belt": "../audio_files/leather_belt.mp3",
}

module.exports = { soundBoard };
